username,website,email,password,created_date,notes
islam,facebook.com,xojambetov73@gmail.com,HsCG{S.&Th+e1|1O?po=*8-TTGLd;5:7bR(*|&]7g,2025-06-28 23:37:45,
islam,github.com,jnx73@gmail.com,vijijevijv9egi03g1igirbuir9birbgt88g5g85h84,2025-06-28 23:42:23,
jinx73,google.com,khisaax@gmail.com,"TypeError TypeError: PasswordGenerator.generate_password() got an unexpected keyword argument 'include_numbers'. Did you mean 'include_symbols'?  Traceback (most recent call last) File ""/Users/xojambetov_islam/PycharmProjects/PasswordGenerator/.venv/lib/python3.13/site-packages/flask/app.py"", line 2213, in __call__ return self.wsgi_app(environ, start_response)        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/Users/xojambetov_islam/PycharmProjects/PasswordGenerator/.venv/lib/python3.13/site-packages/flask/app.py"", line 2193, in wsgi_app response = self.handle_exception(e)            ^^^^^^^^^^^^^^^^^^^^^^^^ File ""/Users/xojambetov_islam/PycharmProjects/PasswordGenerator/.venv/lib/python3.13/site-packages/flask/app.py"", line 2190, in wsgi_app response = self.full_dispatch_request()            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/Users/xojambetov_islam/PycharmProjects/PasswordGenerator/.venv/lib/python3.13/site-packages/flask/app.py"", line 1486, in full_dispatch_request rv = self.handle_user_exception(e)      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/Users/xojambetov_islam/PycharmProjects/PasswordGenerator/.venv/lib/python3.13/site-packages/flask/app.py"", line 1484, in full_dispatch_request rv = self.dispatch_request()      ^^^^^^^^^^^^^^^^^^^^^^^ File ""/Users/xojambetov_islam/PycharmProjects/PasswordGenerator/.venv/lib/python3.13/site-packages/flask/app.py"", line 1469, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File ""/Users/xojambetov_islam/PycharmProjects/PasswordGenerator/app.py"", line 133, in generate_password password = generator.generate_password(             TypeError: PasswordGenerator.generate_password() got an unexpected keyword argument 'include_numbers'. Did you mean 'include_symbols'?",2025-06-28 23:49:25,
